Creating seed job on jenkins init

diff --git a/jenkins_docker/Dockerfile b/jenkins_docker/Dockerfile
--- a/jenkins_docker/Dockerfile
+++ b/jenkins_docker/Dockerfile
@@ -46,6 +46,8 @@ RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
 
 COPY init_scripts/* /usr/share/jenkins/ref/init.groovy.d/
 
+COPY seed-job-creator.groovy /seed-job-creator.groovy
+
 ARG ROOT_URL
 
 RUN if [ -z "$ROOT_URL" ]; then echo "ERROR: ROOT_URL not set"; exit 1; fi
@@ -70,6 +72,10 @@ ARG GITHUB_ACCESS_TOKEN
 
 RUN if [ -z "$GITHUB_ACCESS_TOKEN" ]; then echo "ERROR: GITHUB_ACCESS_TOKEN not set"; exit 1; fi
 
+ARG SEED_JOB_REPO_URL
+
+RUN if [ -z "$SEED_JOB_REPO_URL" ]; then echo "ERROR: SEED_JOB_REPO_URL not set"; exit 1; fi
+
 RUN sed -i "s|ROOT_URL|${ROOT_URL}|g" /usr/share/jenkins/ref/init.groovy.d/configure-root-url.groovy
 
 RUN sed -i "s/JENKINS_USER_NAME/${JENKINS_USER_NAME}/g" /usr/share/jenkins/ref/init.groovy.d/configure-credentials.groovy
@@ -81,4 +87,6 @@ RUN sed -i "s/FIRST_NAME/${FIRST_NAME}/g" /usr/share/jenkins/ref/init.groovy.d/c
 RUN sed -i "s/GITHUB_USER_NAME/${GITHUB_USER_NAME}/g" /usr/share/jenkins/ref/init.groovy.d/configure-github-credentials.groovy
 
 RUN sed -i "s/GITHUB_ACCESS_TOKEN/${GITHUB_ACCESS_TOKEN}/g" /usr/share/jenkins/ref/init.groovy.d/configure-github-credentials.groovy
+
+RUN sed -i "s|SEED_JOB_REPO_URL|${SEED_JOB_REPO_URL}|g" /seed-job-creator.groovy
 
