GIT config for jenkins image

diff --git a/jenkins_docker/Dockerfile b/jenkins_docker/Dockerfile
--- a/jenkins_docker/Dockerfile
+++ b/jenkins_docker/Dockerfile
@@ -6,13 +6,7 @@ COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
 
 RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
 
-COPY configure-credentials.groovy /usr/share/jenkins/ref/init.groovy.d/configure-credentials.groovy
-
-COPY disable-cli.groovy /usr/share/jenkins/ref/init.groovy.d/disable-cli.groovy
-
-COPY configure-root-url.groovy /usr/share/jenkins/ref/init.groovy.d/configure-root-url.groovy
-
-COPY enable-csrf-protection.groovy /usr/share/jenkins/ref/init.groovy.d/enable-csrf-protection.groovy
+COPY init_scripts/* /usr/share/jenkins/ref/init.groovy.d/
 
 ARG ROOT_URL
 
@@ -26,11 +20,17 @@ ARG USER_PASS
 
 RUN if [ -z "$USER_PASS" ]; then echo "ERROR: USER_PASS not set"; exit 1; fi
 
+ARG FIRST_NAME
+
+RUN if [ -z "$FIRST_NAME" ]; then echo "ERROR: FIRST_NAME not set"; exit 1; fi
+
 RUN sed -i "s|ROOT_URL|${ROOT_URL}|g" /usr/share/jenkins/ref/init.groovy.d/configure-root-url.groovy
 
 RUN sed -i "s/USER_NAME/${USER_NAME}/g" /usr/share/jenkins/ref/init.groovy.d/configure-credentials.groovy
 
 RUN sed -i "s/USER_PASS/${USER_PASS}/g" /usr/share/jenkins/ref/init.groovy.d/configure-credentials.groovy
+
+RUN sed -i "s/FIRST_NAME/${FIRST_NAME}/g" /usr/share/jenkins/ref/init.groovy.d/configure-git-global-config.groovy
 
 USER root
 
@@ -49,3 +49,7 @@ RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debia
 RUN apt-get update;\
     apt-get install -y docker-ce="18.06.1~ce~3-0~debian"; \
     usermod -aG docker jenkins
+
+USER jenkins
+
+RUN git config --global user.name jenkins; cat ~/.gitconfig;
